@startuml Activity Diagram
start
:User enters search input;
if (Input is URL?) then (yes)
  :Call POST /scrape/url;
  :Backend scraps product data;
  :Display search success alert;
  :Navigate to Watchlist;
else (no)
  :User selects Category;
  :Call POST /scrape/category;
  :Backend finds product candidates;
  if (Candidates found?) then (yes)
    :Display CandidateSelection view;
    :User selects one or more candidates;
    :User clicks "Track Selected";
    :Call POST /products/bulk;
    :Display success alert;
    :Navigate to Watchlist;
  else (no)
    :Display "No products found" error;
  endif
endif
:App re-fetches products & trackings;
:Update Dashboard;
stop
@enduml
